import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar/sidebar";
import { AppSidebar } from "@/components/Sidebar/app-sidebar";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/navbar/Navbar";
import { DashboardProviders } from "@/components/levels/DashboardProviders"
import { ChatWidget } from "@/components/chatbot/chatwidget";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <DashboardProviders>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <Navbar />
            <ChatWidget />
            <div className="relative z-0 min-w-0 flex-1 overflow-auto px-4 py-4 sm:px-6 sm:py-5 lg:px-8 lg:py-0">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
      </DashboardProviders>
    </ThemeProvider>
  );
}